version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: daily
    groups:
      python:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
